### ISSUE TITLE
Seems like vagrant version 1.7.0 is not supported

### ISSUE THREAD

**Issue by d34dman** [factorial-io/multibasebox#5]
I had to upgrade to vagrant version 1.8.1 to get it working.

**Comment by stmh** [comment]
strange, I am using Vagrant 1.7.4. What was the problem?

**Comment by d34dman** [comment]
my vagrant dns is not working, so i had to edit the host files to access the project sites.

This is the behaviour which i had observed,
1. http://multibasebox.dev:1936 was accessible and it listed the statistics.
2. if we do `fab config:mbb docker:run` inside projects, it used to time out after `wait for services` message.
3. upgrading to 1.8.1 resolved the issue.
