### ISSUE TITLE
Vagrant DNS doens't seem to work 

### ISSUE THREAD

**Issue by MuschPusch** [factorial-io/multibasebox#7]
On a clean install we have the problem that vagrant DNS doesn't seem to work @stmh didn't you had a similar problem?

Workaround is adding entries to /etc/hosts of the host computer. 

33.33.33.33 bla.dev

**Comment by stmh** [comment]
try running `vagrant das --install` again and check the output of `dscacheutil -q host -a name multibasebox.dev`
